# Generated by Django 3.0.4 on 2020-03-12 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creteTime'),
        ),
    ]
