# Generated by Django 3.0.4 on 2020-03-17 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20200314_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadfile',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='downloadUserId',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='uploadUserId',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='userId',
        ),
        migrations.AddField(
            model_name='downloadfile',
            name='userID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='userId'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='userId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='userId'),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='userID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='userId'),
        ),
        migrations.AlterField(
            model_name='downloadfile',
            name='fileId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UploadFile', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='fileId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UploadFile', verbose_name='file'),
        ),
    ]
