# Generated by Django 3.0.4 on 2020-03-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200317_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='filePath',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='filePath'),
        ),
    ]
