# Generated by Django 3.0.4 on 2020-03-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_receipt_nrr'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadfile',
            name='nro',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='nro'),
        ),
    ]
