# Generated by Django 3.0.4 on 2020-03-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_downloadfile_nro'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadfile',
            name='nro_original',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='nro_original'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='nrr_originial',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='nrr_originial'),
        ),
    ]
